/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.checkerframework.languageserver;

import java.io.File;
import java.io.IOException;

public class DownloaderMain {
    public static void main(String[] args) {
        if (args.length != 1) {
            System.out.println("args: path-to-a-folder");
            System.exit(1);
        }

        File folder = new File(args[0]);
        if (!folder.isDirectory()) {
            System.err.println("The path provided is not a folder: " + args[0]);
        }

        BaseDownloader d;

        try {
            d = new LanguageServerDownloader(folder);
            File f = d.download();
            System.out.println("Got " + f.getAbsolutePath());
        } catch (IOException e) {

        }

        try {
            d = new CheckerFrameworkDownloader(folder);
            File f = d.download();
            System.out.println("Got " + f.getAbsolutePath());
        } catch (IOException e) {

        }
    }
}
